name: Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ master ]

jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python unit_tests/test_my_utils.py
  run_func_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash func_tests/test_print_fires.sh
  run_style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install pycodestyle
      - run: pycodestyle *.py